/*
 * ina219_defines.hpp
 *
 *  Created on: Sep 29, 2025
 *      Author: Oleksiy
 */

#ifndef NIKOLEX_INA219_INA219_DEFINES_HPP_
#define NIKOLEX_INA219_INA219_DEFINES_HPP_

namespace nikolex::ina219 {

	enum ADC_RESOLUTION_AVERAGING : uint16_t  {
		BIT_9,
		BIT_10,
		BIT_11,
		BIT_12 = 0b1000,
		SAMPLES_2,
		SAMPLES_4,
		SAMPLES_8,
		SAMPLES_16,
		SAMPLES_32,
		SAMPLES_64,
		SAMPLES_128
	};

	enum MODE : uint16_t  {
		POWER_DOWN_MODE,
		SHUNT_VOLTAGE_TRIGGERED_MODE,
		BUS_VOLTAGE_TRIGGERED_MODE,
		SHUNT_AND_BUS_TRIGGERED_MODE,
		ADC_OFF_MODE,
		SHUNT_VOLTAGE_CONTINUOUS_MODE,
		BUS_VOLTAGE_CONTINUOUS_MODE,
		SHUNT_AND_BUS_CONTINUOUS_MODE
	};

	enum PGA : uint16_t {
		RANGE_40mV_GAIN_1,
		RANGE_80mV_GAIN_2,
		RANGE_160mV_GAIN_4,
		RANGE_320mV_GAIN_8,
	};


	enum BUS_VOLTAGE_RANGE : uint16_t {
		RANGE_16V,
		RANGE_32V
	};

	enum Event {
		NONE,
		READ_REGISTER,
		WRITE_REGISTER,
		MODIFY_REGISTER,
		READ_CURRENT,
		READ_SHUNT_VOLTAGE,
		READ_BUS_VOLTAGE,
		WAIT_CONVERSION,
	};

}



#endif /* NIKOLEX_INA219_INA219_DEFINES_HPP_ */
